[theme]
primaryColor="#3498db"  # Blue color for primary elements
backgroundColor="#f5f5f5"  # Light gray background
secondaryBackgroundColor="#ecf0f1"  # Slightly darker background
textColor="#333333"  # Dark text color for readability
font="Arial, sans-serif"  # Clean and professional font
