[theme]
primaryColor="#3498db"  # Vibrant blue primary color
backgroundColor="#f8f9fa"  # Light grayish background
secondaryBackgroundColor="#e9ecef"  # Slightly darker background
textColor="#212529"  # Dark text color for contrast
font="Roboto, sans-serif"  # Modern and sleek font
