[theme]
primaryColor="#3498db"  # Vibrant blue primary color
backgroundColor="#2c3e50"  # Dark blue-gray background
secondaryBackgroundColor="#34495e"  # Medium blue-gray background
textColor="#ffffff"  # White text color for contrast
font="Roboto, sans-serif"  # Modern and sleek font
